//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_starcatchercontroller : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean set_star_position
        {
            get
            {
                return SteamVR_Actions.starcatchercontroller_set_star_position;
            }
        }
        
        public virtual SteamVR_Action_Boolean clear_star_positions
        {
            get
            {
                return SteamVR_Actions.starcatchercontroller_clear_star_positions;
            }
        }
        
        public virtual SteamVR_Action_Boolean scene_change
        {
            get
            {
                return SteamVR_Actions.starcatchercontroller_scene_change;
            }
        }
    }
}
