//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_starcatchercontroller : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Controller_click
        {
            get
            {
                return SteamVR_Actions.starcatchercontroller_Controller_click;
            }
        }
        
        public virtual SteamVR_Action_Vector3 InputSet
        {
            get
            {
                return SteamVR_Actions.starcatchercontroller_InputSet;
            }
        }
    }
}
